feat: updated workflows for build and for build and release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,6 +1,5 @@
 name: Release and publish to sfw.evva.com
 on:
-  push:
   workflow_dispatch:
     inputs:
       input_version:
@@ -12,12 +11,19 @@ on:
           - minor
           - major
 concurrency: ${{ github.workflow }}-${{ github.ref }}
+
 # Dont need permissions because we use github app and not the workflow permissions
 permissions: {}
 jobs:
   publish:
     runs-on: ubuntu-latest
     steps:
+      - name: Check valid release input choice
+        run: |
+          if [ -z "${{ github.event.inputs.input_version }}" ]; then
+            echo "[ERROR] You must select either major, minor or patch type of release when executing workflow!"
+            exit 1
+          fi
       - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
         id: app-token
         with:
@@ -73,53 +79,6 @@ jobs:
 
           cat ${{ github.workspace }}/Sources/xs3-cert/versioninfo.swift
 
-      #####################################################
-      # - name: Run release-it only bump version and generate changelog
-      #   run: npx release-it ${{ github.event.inputs.input_version }} --ci --no-github.release
-      #   env:
-      #     GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
-      # - name: Extract current version
-      #   id: version
-      #   run: |
-      #     BIN_VERSION=$(grep "version" ${{ github.workspace }}/Sources/xs3-cert/versioninfo.swift | sed -E 's/.*"(.*)".*/\1/')
-      #     echo "BIN_VERSION=$BIN_VERSION" >> "$GITHUB_OUTPUT"
-
-      # - name: Create commit message
-      #   run: |
-      #     echo "chore: release ${{ steps.version.outputs.new }}" > commitMessageFile
-      # - name: Commit changes
-      #   uses: iarekylew00t/verified-bot-commit@68c52beb4042b7038cf40c4daf6e469f118c686b # v2.0.5
-      #   id: commit
-      #   with:
-      #     message-file: commitMessageFile
-      #     token: ${{ steps.app-token.outputs.token }}
-      #     if-no-commit: notice
-      #     update-local: true
-      #     files: |
-      #       CHANGELOG.md
-      #       VERSION
-      # - name: Create Tag
-      #   run: |
-      #     curl -X POST \
-      #       -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
-      #       -H "Accept: application/vnd.github+json" \
-      #       https://api.github.com/repos/${{ github.repository }}/git/refs \
-      #       -d @- <<EOF
-      #     {
-      #       "ref": "refs/tags/${{ steps.version.outputs.BIN_VERSION }}",
-      #       "sha": "${{ github.sha }}"
-      #     }
-      #     EOF
-      # # Checkout the latest commit
-      # - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      #   with:
-      #     token: ${{ steps.app-token.outputs.token }}
-      #     ref: ${{ github.head_ref }}
-      #     # Make sure the value of GITHUB_TOKEN will persist in repo's config for release-it to use it later
-      #     # In this case it is a short lived app-token, so its ok
-      #     persist-credentials: true
-      #     fetch-depth: 0 # For release-it and auto-changelog to be able to generate the full changelog
-#####################################################33
 
       # Install Swift and SDK
       - name: Install dependencies
@@ -184,12 +143,10 @@ jobs:
               --query "{Name:name, size: properties.contentLength, lastModified: properties.lastModified, creationTime: properties.creationTime }"   \
               --output table 2>/dev/null
 
-      
-
       # Generate Changelog and release
       - name: Install node dependencies
         run: npm ci
       - name: Run release-it only create release on github
-        run: npx release-it ${{ github.event.inputs.input_version || 'patch' }} --ci
+        run: npx release-it ${{ github.event.inputs.input_version }} --ci
         env:
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
